version: '1.0'
services:
  iscow_backend:
    container_name: iscow_backend
    image: iscow/iscow_template:0.0.1
    build: 
      context: .
    ports:
    - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=admin
      - PGPASSWORD=iscowin
      - PGDATABASE=iscowin
      - PGHGOST=iscowin_db
    depends_on:
      - iscowin_db
  iscowin_db:
    container_name: iscowin_db
    image: "postgres:12"   
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=iscowin
      - POSTGRES_DB=iscowin_db
    volumes:
      - iscowin_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  iscowin_data: {}

  